name: mulcryptdb
channels:
  - conda-forge
  - defaults
dependencies:
  - audioread=3.0.1=py38haa244fe_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.0.9=py38hd3f51b4_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h4cb3324_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - fonttools=4.53.1=py38h4cb3324_0
  - freetype=2.14.1=h57928b3_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38hb1fd069_1
  - lame=3.100=hcfcfb64_1003
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=2_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=2_h2a3cdd5_mkl
  - libdeflate=1.25=h51727cc_0
  - libffi=3.4.4=hd77b12b_1
  - libflac=1.4.3=h63175ca_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=2_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.51=h7351971_0
  - librosa=0.10.2.post1=pyhd8ed1ab_0
  - libsndfile=1.2.2=h81429f1_1
  - libtiff=4.7.1=h8f73337_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - llvmlite=0.41.1=py38h19421c1_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.7.3=py38h2724991_0
  - mkl=2025.3.0=hac47afa_454
  - mpg123=1.32.9=h01009b0_0
  - msgpack-python=1.0.8=py38h7b008d5_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - numba=0.58.1=py38h4a59444_0
  - numpy=1.24.4=py38h1d91fd2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=25.0=pyh29332c3_1
  - pillow=10.4.0=py38h8d10685_0
  - pip=24.2=py38haa95532_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.8.18=h6244533_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - requests=2.32.3=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38h4f736e5_2
  - scipy=1.10.1=py38h1aea9ed_3
  - setuptools=75.1.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - soxr=0.1.3=hcfcfb64_3
  - soxr-python=0.3.7=py38he7056a7_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h2c6b04d_3
  - typing_extensions=4.12.2=pyha770c72_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - zstandard=0.19.0=py38h91455d4_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - anyio==4.5.2
      - av==12.3.0
      - beautifulsoup4==4.14.2
      - bitarray==3.8.0
      - blinker==1.8.2
      - chardet==3.0.4
      - click==8.1.8
      - colorama==0.4.6
      - cython==3.2.1
      - deep-translator==1.11.4
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - filelock==3.13.1
      - flask==3.0.3
      - flask-cors==5.0.0
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - fvcore==0.1.5.post20221221
      - googletrans==3.1.0a0
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - huggingface-hub==0.36.0
      - hyperframe==5.2.0
      - idna==2.10
      - iopath==0.1.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - libretranslatepy==2.1.1
      - lxml==6.0.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.0
      - opencv-python==4.12.0.88
      - parameterized==0.9.0
      - portalocker==3.0.0
      - pycryptodome==3.23.0
      - pytorchvideo==0.1.5
      - pywin32==311
      - pyyaml==6.0.3
      - regex==2024.11.6
      - rfc3986==1.5.0
      - safetensors==0.5.3
      - sniffio==1.3.1
      - soupsieve==2.7
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - timm==1.0.22
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - translate==3.8.0
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - yacs==0.1.8
      - zipp==3.20.2
prefix: E:\Anaconda3\envs\mulcryptdb
